# Generated by Django 4.0.4 on 2022-06-05 12:00

import awesome_avatar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=awesome_avatar.fields.AvatarField(upload_to='media'),
        ),
    ]
